services:
  dashboard:
    image: localhost:5000/slak-dashboard:latest
    container_name: stock-dashboard
    environment:
      # PostgreSQL connection (required)
      - DB_HOST=192.168.1.90
      - DB_PORT=5434
      - DB_NAME=stock_quotes
      - DB_USER=scott
      - DB_PASSWORD=changeme
      # Alpha Vantage (required only for Fetch Latest Quotes action)
      - AV_API_KEY=changeme
      - TICKERS_STOCKS=QBTS,IONQ,RGTI,QUBT,FORM,SOXQ,IBIT,VFIAX,PIMIX,SWPPX,VOO,TRRDX,QQQM,FFIV,NET,BE,FRVO,GEV,NXT,FLNC,PLUG,ENVX,SNOW,FTNT,ATEN,AKAM,CRWD,PLTR,SPY,NASDX
      - TICKERS_CRYPTO=GTC,ETH,XRP
    ports:
      - "8050:8050"
    restart: unless-stopped
